/**
 * @fileoverview gRPC-Web generated client stub for category.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.11.4
// source: proto/v1/category.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.category = {};
proto.category.v1 = require('./category_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.category.v1.CategoryClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.category.v1.CategoryPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.category.v1.CategoryGetAllResponce>}
 */
const methodDescriptor_Category_GetAll = new grpc.web.MethodDescriptor(
  '/category.v1.Category/GetAll',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.category.v1.CategoryGetAllResponce,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.category.v1.CategoryGetAllResponce.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.category.v1.CategoryGetAllResponce)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.category.v1.CategoryGetAllResponce>|undefined}
 *     The XHR Node Readable Stream
 */
proto.category.v1.CategoryClient.prototype.getAll =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/category.v1.Category/GetAll',
      request,
      metadata || {},
      methodDescriptor_Category_GetAll,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.category.v1.CategoryGetAllResponce>}
 *     Promise that resolves to the response
 */
proto.category.v1.CategoryPromiseClient.prototype.getAll =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/category.v1.Category/GetAll',
      request,
      metadata || {},
      methodDescriptor_Category_GetAll);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.category.v1.CategoryGetRequest,
 *   !proto.category.v1.CategoryGetResponce>}
 */
const methodDescriptor_Category_Get = new grpc.web.MethodDescriptor(
  '/category.v1.Category/Get',
  grpc.web.MethodType.UNARY,
  proto.category.v1.CategoryGetRequest,
  proto.category.v1.CategoryGetResponce,
  /**
   * @param {!proto.category.v1.CategoryGetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.category.v1.CategoryGetResponce.deserializeBinary
);


/**
 * @param {!proto.category.v1.CategoryGetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.category.v1.CategoryGetResponce)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.category.v1.CategoryGetResponce>|undefined}
 *     The XHR Node Readable Stream
 */
proto.category.v1.CategoryClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/category.v1.Category/Get',
      request,
      metadata || {},
      methodDescriptor_Category_Get,
      callback);
};


/**
 * @param {!proto.category.v1.CategoryGetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.category.v1.CategoryGetResponce>}
 *     Promise that resolves to the response
 */
proto.category.v1.CategoryPromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/category.v1.Category/Get',
      request,
      metadata || {},
      methodDescriptor_Category_Get);
};


module.exports = proto.category.v1;

