/**
 * @fileoverview gRPC-Web generated client stub for order.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.11.4
// source: proto/v1/order.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.order = {};
proto.order.v1 = require('./order_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.order.v1.OrderClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.order.v1.OrderPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.order.v1.PlaceRequest,
 *   !proto.order.v1.OrderStatusResponce>}
 */
const methodDescriptor_Order_Place = new grpc.web.MethodDescriptor(
  '/order.v1.Order/Place',
  grpc.web.MethodType.UNARY,
  proto.order.v1.PlaceRequest,
  proto.order.v1.OrderStatusResponce,
  /**
   * @param {!proto.order.v1.PlaceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.order.v1.OrderStatusResponce.deserializeBinary
);


/**
 * @param {!proto.order.v1.PlaceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.order.v1.OrderStatusResponce)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.order.v1.OrderStatusResponce>|undefined}
 *     The XHR Node Readable Stream
 */
proto.order.v1.OrderClient.prototype.place =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/order.v1.Order/Place',
      request,
      metadata || {},
      methodDescriptor_Order_Place,
      callback);
};


/**
 * @param {!proto.order.v1.PlaceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.order.v1.OrderStatusResponce>}
 *     Promise that resolves to the response
 */
proto.order.v1.OrderPromiseClient.prototype.place =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/order.v1.Order/Place',
      request,
      metadata || {},
      methodDescriptor_Order_Place);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.order.v1.OrderStatusRequest,
 *   !proto.order.v1.OrderStatusResponce>}
 */
const methodDescriptor_Order_GetOrderStatus = new grpc.web.MethodDescriptor(
  '/order.v1.Order/GetOrderStatus',
  grpc.web.MethodType.UNARY,
  proto.order.v1.OrderStatusRequest,
  proto.order.v1.OrderStatusResponce,
  /**
   * @param {!proto.order.v1.OrderStatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.order.v1.OrderStatusResponce.deserializeBinary
);


/**
 * @param {!proto.order.v1.OrderStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.order.v1.OrderStatusResponce)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.order.v1.OrderStatusResponce>|undefined}
 *     The XHR Node Readable Stream
 */
proto.order.v1.OrderClient.prototype.getOrderStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/order.v1.Order/GetOrderStatus',
      request,
      metadata || {},
      methodDescriptor_Order_GetOrderStatus,
      callback);
};


/**
 * @param {!proto.order.v1.OrderStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.order.v1.OrderStatusResponce>}
 *     Promise that resolves to the response
 */
proto.order.v1.OrderPromiseClient.prototype.getOrderStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/order.v1.Order/GetOrderStatus',
      request,
      metadata || {},
      methodDescriptor_Order_GetOrderStatus);
};


module.exports = proto.order.v1;

