/**
 * @fileoverview gRPC-Web generated client stub for product.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.11.4
// source: proto/v1/product.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.product = {};
proto.product.v1 = require('./product_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.product.v1.ProductClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.product.v1.ProductPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.product.v1.ProductGetAllRequest,
 *   !proto.product.v1.ProductGetAllResponce>}
 */
const methodDescriptor_Product_GetAll = new grpc.web.MethodDescriptor(
  '/product.v1.Product/GetAll',
  grpc.web.MethodType.UNARY,
  proto.product.v1.ProductGetAllRequest,
  proto.product.v1.ProductGetAllResponce,
  /**
   * @param {!proto.product.v1.ProductGetAllRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.product.v1.ProductGetAllResponce.deserializeBinary
);


/**
 * @param {!proto.product.v1.ProductGetAllRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.product.v1.ProductGetAllResponce)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.product.v1.ProductGetAllResponce>|undefined}
 *     The XHR Node Readable Stream
 */
proto.product.v1.ProductClient.prototype.getAll =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/product.v1.Product/GetAll',
      request,
      metadata || {},
      methodDescriptor_Product_GetAll,
      callback);
};


/**
 * @param {!proto.product.v1.ProductGetAllRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.product.v1.ProductGetAllResponce>}
 *     Promise that resolves to the response
 */
proto.product.v1.ProductPromiseClient.prototype.getAll =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/product.v1.Product/GetAll',
      request,
      metadata || {},
      methodDescriptor_Product_GetAll);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.product.v1.ProductGetRequest,
 *   !proto.product.v1.ProductGetResponce>}
 */
const methodDescriptor_Product_Get = new grpc.web.MethodDescriptor(
  '/product.v1.Product/Get',
  grpc.web.MethodType.UNARY,
  proto.product.v1.ProductGetRequest,
  proto.product.v1.ProductGetResponce,
  /**
   * @param {!proto.product.v1.ProductGetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.product.v1.ProductGetResponce.deserializeBinary
);


/**
 * @param {!proto.product.v1.ProductGetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.product.v1.ProductGetResponce)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.product.v1.ProductGetResponce>|undefined}
 *     The XHR Node Readable Stream
 */
proto.product.v1.ProductClient.prototype.get =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/product.v1.Product/Get',
      request,
      metadata || {},
      methodDescriptor_Product_Get,
      callback);
};


/**
 * @param {!proto.product.v1.ProductGetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.product.v1.ProductGetResponce>}
 *     Promise that resolves to the response
 */
proto.product.v1.ProductPromiseClient.prototype.get =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/product.v1.Product/Get',
      request,
      metadata || {},
      methodDescriptor_Product_Get);
};


module.exports = proto.product.v1;

